import { GetStaticProps } from 'next'
import { VFC } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import home from 'styles/Home.module.scss'
import { getAllPosts } from '../../lib/post'
import { getAllCategories } from '../../lib/category';
import Link from 'next/link'
import Sidebar from "../components/molecules/sidebar";

export const getStaticProps: GetStaticProps = async () => {
  const allPostData = await getAllPosts()
  const allCategory = await getAllCategories();
  return {
    props: {
      allPostData,
      allCategory
    },
  }
}

type category = {
  category: string
}

type eyecatch = {
  url: string
  height: number
  width: number
}

interface Props {
  allPostData: {
    id: string
    title: string
    createdAt: string
    category: category | null
    eyecatch?: eyecatch | null
  }[],
  allCategory: string[]
}

const Home: VFC<Props> = ({ allPostData, allCategory }: Props ) => {
  return (
    <>
      <Head>
        <title>kazの保管庫</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>
      <div className={home.main}>
        <ul className={home.postList}>
          {allPostData && (
            allPostData.map((post) => (
            <li className={home.postRecord} key={post.id}>
              <Link href={`/posts/${post.id}`}>
                <a className={home.postPanel}>
                  {post.eyecatch ? (
                    <Image
                      className={home.img}
                      src={post.eyecatch.url}
                      alt="アイキャッチ画像"
                      width={300}
                      height={300}
                    />
                  ) : (
                    <Image
                      src="/images/free_img_gray.png"
                      alt="フリー画像"
                      width={300}
                      height={300}
                    />
                  )}
                  <div className={home.pannelBottom}>
                    <h2 className={home.recordTitle}>{post.title}</h2>
                    <div className={home.authorInfo}>
                      <span className={home.createdAt}>2020.5.18</span>
                    </div>
                  </div>
                </a>
              </Link>
            </li>
          )
          ))}
        </ul>
      </div>
      <Sidebar allCategory={allCategory} />
    </>
  )
}

export default Home
