import { GetStaticProps } from 'next'
import { VFC, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import home from 'styles/Home.module.scss'
import { getAllPosts } from '../../lib/post'
import { getAllCategories } from '../../lib/category';
import Link from 'next/link'
import Sidebar from "../components/molecules/sidebar";
import {Categories} from "../../types/category"

export const getStaticProps: GetStaticProps<Props> = async () => {
  const allPostData = await getAllPosts()
  const allCategory: Categories = await getAllCategories();
  return {
    props: {
      allPostData,
      allCategory
    },
  }
}

type category = {
  category: string
}

type eyecatch = {
  url: string
  height: number
  width: number
}

interface Props {
  allPostData: {
    id: string
    title: string
    createdAt: string
    updatedAt: string
    category: category | null
    eyecatch?: eyecatch | null
  }[],
  allCategory: Categories
}

const Home: VFC<Props> = ({ allPostData, allCategory }: Props) => {
  const [allPosts] = useState(allPostData);
  const [viewPosts, setViewPosts] = useState(allPostData);

  const searchPosts = (event: React.ChangeEvent<HTMLInputElement>) => {
    console.log("searchPosts: 検索開始")
    console.log(event.target.value);
    const target = event.target.value;
    if (target === "") {
      setViewPosts(allPosts);

    } else {
      const targetPosts = allPosts.filter(post => {
        return (post.title.indexOf(target) > -1);
      });

      setViewPosts(targetPosts);
    }
  }
  return (
    <>
      <Head>
        <title>kazの保管庫</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>
      <div className={home.main}>
        <ul className={home.postList}>
          {viewPosts && (
            viewPosts.map((post) => (
            <li className={home.postRecord} key={post.id}>
              <Link href={`/posts/${post.id}`}>
                <a className={home.postPanel}>
                  {post.eyecatch ? (
                    <Image
                      className={home.img}
                      src={post.eyecatch.url}
                      alt="アイキャッチ画像"
                      width={300}
                      height={300}
                    />
                  ) : (
                    <Image
                      src="/images/free_img_gray.png"
                      alt="フリー画像"
                      width={300}
                      height={300}
                    />
                  )}
                  <div className={home.pannelBottom}>
                    <h2 className={home.recordTitle}>{post.title}</h2>
                    <div className={home.authorInfo}>
                        <span className={home.createdAt}>
                          {post.updatedAt}
                        </span>
                    </div>
                  </div>
                </a>
              </Link>
            </li>
          )
          ))}
        </ul>
      </div>
      <Sidebar categories={allCategory} inputSeach={searchPosts}/>
    </>
  )
}

export default Home
